Dataset：https://www.kaggle.com/tanlikesmath/the-oxfordiiit-pet-dataset
model_fit.py 后再运行 seg_2.py
a little bug : model.h5 cannot be loaded normally after save_model, so you need to put the seg_2 code into the Python Console to run
